import { ReactNode } from "react";
import { BsCurrencyExchange, BsCalendarDay } from "react-icons/bs";
import { AiOutlineStock, AiFillHome } from "react-icons/ai";
import Link from "next/link";
import Head from "next/head";
import Commodity from "@/public/commodity-indigo.png";
import Image from "next/image";
export default function Layout({ children }: { children: ReactNode }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row w-screen">
        <nav className="flex flex-col items-center gap-3 py-3 text-3xl shadow-md w-28">
          <Link
            role="button"
            href="/"
            // hover:bg-indigo-700 hover:text-white
            className="flex items-center justify-center w-12 h-12 text-indigo-900 rounded-md"
          >
            <AiFillHome />
          </Link>
          <Link
            role="button"
            href="/currencies"
            className="flex items-center justify-center w-12 h-12 text-indigo-900 rounded-md"
          >
            <BsCurrencyExchange />
          </Link>
          <Link
            role="button"
            href="/indices"
            className="flex items-center justify-center w-12 h-12 text-indigo-900 rounded-md"
          >
            <AiOutlineStock />
          </Link>
          <Link
            role="button"
            href="/commodities"
            className="flex items-center justify-center w-12 h-12 text-indigo-900 rounded-md"
          >
            <Image src={Commodity} width="36" height="36" alt="" />
          </Link>
        </nav>
        <main className="flex flex-col min-h-screen gap-3 p-3 grow bg-grey-100">
          {children}
        </main>
      </div>
    </>
  );
}
